---
- debug:
    msg: "apt install {{ apt_tools_to_install }}"

- name: Install apt tools
  apt:
    name: "{{ apt_tools_to_install }}"
    state: present
    update_cache: yes
    cache_valid_time: 600
  become: yes
