---
# Install pyenv
# Dotfiles sets up all necessary environment variables

- name: Clone pyenv repo
  git:
    repo: '{{ pyenv.repo }}'
    version: '{{ pyenv.version }}'
    dest: "{{ ansible_env.HOME }}/.pyenv"
    update: no

- name: Clone pyenv-virtualenv repo
  git:
    repo: '{{ pyenv_virtualenv.repo }}'
    version: '{{ pyenv_virtualenv.version }}'
    dest: "{{ ansible_env.HOME }}/.pyenv/plugins/pyenv-virtualenv"
    update: no

#
# Usage:
#
# pyenv install 3.6.9
# pyenv virtualenv 3.6.9 mpd_3.6
# pyenv activate mpd_3.6
# pyenv global mpd_3.6
#
