---
- name: Install apt packages
  apt:
    name: "{{ gnome_apt_to_install }}"
    state: present
    update_cache: no
  become: yes

- name: Check Key Existence
  dconf:
    key: "{{ item.key}}"
    state: read
  with_items: "{{ gnome_preferences }}"

- name: Preferences
  dconf:
    key: "{{ item.key }}"
    value: "{{ item.value | string }}"
    state: present
  with_items: "{{ gnome_preferences }}"


#
# TODO: Install GNOME shell extensions
#
# appindicatorsupport@rgcjonas.gmail.com/
# freon@UshakovVasilii_Github.yahoo.com/
# impatience@gfxmonk.net/
# pixel-saver@deadalnix.me/
# ProxySwitcher@flannaghan.com/
# sound-output-device-chooser@kgshank.net/
#