---
- name: Install apt packages
  apt:
    name: "{{ gnome_apt_to_install }}"
    state: present
    update_cache: no
  become: yes

# This background image is in ubuntu-wallpapers-artful
- name: Set desktop background
  dconf:
    key: /org/gnome/desktop/background/picture-uri
    value: "'file:///usr/share/backgrounds/Grand_Canyon_North_Rim_by_Rihards_Vilks.jpg'"
