---
- name: Create ~/src if it does not exist
  file:
    path: '{{ ansible_env.HOME }}/src'
    state: directory
    mode: '0755'

- name: Clone Gogh repo
  git:
    repo: '{{ gogh_repo.repo }}'
    version: '{{ gogh_repo.version }}'
    dest: '{{ ansible_env.HOME }}/src/gogh'
    update: no

# On Ubuntu, ensure that a profile named "Default" is created first,
# else Ubuntu 19.10+ will fail
# https://github.com/Mayccoll/Gogh/issues/203

- name: Look for existing profiles
  command: dconf list /org/gnome/terminal/
  register: dconf_list_terminal
  when: ansible_distribution == "Ubuntu"

- name: Confirm Default profile exists
  assert:
    that: dconf_list_terminal.stdout != ""
    fail_msg: "Missing prerequisite: Please manually create a 'Default' profile in Terminal and retry."
  when: ansible_distribution == "Ubuntu"

- name: Install Gogh themes
  shell:
    cmd: './{{ item }}.sh'
    chdir: '{{ ansible_env.HOME }}/src/gogh/themes'
    executable: /bin/bash
  environment:
    TERMINAL: gnome-terminal
    BASE_URL: 'never-allow-wget-pipe-to-bash'
  loop: "{{ gogh_themes }}"
