---
# Howto: https://support.1password.com/getting-started-linux/

- name: Add the key for the 1Password apt repository
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3FEF9748469ADBE15DA7CA80AC2D62742012EA22
    keyring: /usr/share/keyrings/1password.gpg
  become: yes

- name: Add the 1Password apt repository
  template:
    src: templates/apt/1password.list.j2
    dest: "/etc/apt/sources.list.d/1password.list"
  become: yes
  register: repo

- name: Update apt cache
  apt:
    update_cache: yes
  become: yes
  when: repo.changed

- name: Install 1Password
  apt:
    name: 1password
  become: yes
