---
- name: gitconfig
  template:
    src: templates/apt/sublime-text.list
    dest: "/etc/apt/sources.list.d/sublime-text.list"
  become: yes

- name: Add Sublime Apt signing key
  apt_key:
    id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present

- name: Install Sublime Text
  apt:
    name: [sublime-text, sublime-merge]
    state: present
    update_cache: yes
    cache_valid_time: 600
  become: yes
