---
- assert:
    that: "ansible_os_family == 'Debian'"

- name: Add apt sources.list
  template:
    src: templates/apt/sublime-text.list
    dest: "/etc/apt/sources.list.d/sublime-text.list"
  become: yes

- name: Add Sublime Apt signing key
  apt_key:
    id: 1EDDE2CDFC025D17F6DA9EC0ADAE6AD28A8F901A
    url: https://download.sublimetext.com/sublimehq-pub.gpg
    state: present
  become: yes

- name: Install Sublime Text
  apt:
    name: [sublime-text, sublime-merge]
    state: present
    update_cache: yes
    cache_valid_time: 600
  become: yes

- name: Create Sublime config dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages"
    - "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User"

- name: Install packages
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Installed Packages"
  with_fileglob:
    - files/packages/*

- name: Install configs
  template:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/User"
  with_fileglob:
    - templates/User/*

- name: Install configs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/Packages/User"
  with_fileglob:
    - templates/User/*

- name: Install User prefs
  copy:
    src: "{{ item }}"
    dest: "{{ ansible_env.HOME }}/.config/sublime-text-3/User"
  with_fileglob:
    - templates/User/Preferences.sublime-settings
