---
apt_tools_to_install:
  - build-essential
  - git
  - iotop
  - python3-dev
  - python3-pip
  - python3-venv
  - tig
  - unzip
  - vim
  - zip

  # # getting fresher version of awscli requires pip3 :(
  # - awscli
  # - python-boto3
  # - htop
  # - mediainfo
  # - molly-guard
  # - nmap
  # - traceroute
  # - libmysqlclient-dev
  # - postgresql-client
  # - libssl-dev
