---

- hosts: laptop

  # environment:

  roles:
    - role: base
      tags: base
    - role: gnome-desktop
    - role: gogh
      tags: gogh
    - role: sublime-text
    - role: virtualbox
      tags: vbox
    - role: vpn-pulse-secure
      tags: pulse
    - role: 1password
      tags: 1password
    # - role: dropbox

  tasks:
    - name: "Install apt: GPaste, Pulse Audio Volume Control"
      become: yes
      apt:
        name:
          - gpaste
          - gnome-shell-extensions-gpaste
          - pavucontrol
        state: present

    - name: "Install Snaps: Okular, Slack, Spotify"
      become: yes
      snap:
        name:
          - okular
          - slack
          - spotify

# Some other useful Snaps, but not always necessary for me!
#
# atom                  - FOSS text editor
# inkscape              - FOSS vector graphic drawing
# krita                 - FOSS raster graphics editor, built with Qt
# pycharm-professional
#
