---
- assert:
    that: "ansible_os_family == 'Debian'"

- name: ansible_distribution_release
  debug:
    var: ansible_distribution_release

# ansible_distribution_release is used in the next template

- name: Add apt sources.list
  template:
    src: templates/apt/virtualbox.list
    dest: "/etc/apt/sources.list.d/virtualbox.list"
  become: yes

- name: Add Virtualbox Apt signing key
  apt_key:
    data: "{{ lookup('file', 'oracle_vbox_2016.asc') }}"
    id: B9F8D658297AF3EFC18D5CDFA2F683C52980AECF
    state: present
  become: yes

#
# When virtualbox-dkms is installed the first time, you will be prompted
# to enter a password, reboot, then enter this password to import a
# Machine Owner Key (MOK)
#
# To rerun this in the future, if ever needed,
# sudo dpkg-reconfigure virtualbox-dkms
#

- name: Install Virtualbox with drivers managed by dkms
  apt:
    name: virtualbox-dkms
    state: present
    update_cache: yes
    cache_valid_time: 600
  become: yes

- name: Confirm virtualbox drivers are loaded
  modprobe:
    name: "{{ item }}"
    state: present
  become: yes
  loop:
    - vboxdrv
    - vboxnetflt
    - vboxnetadp
